name: Docker

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        include:
          - base: 'ubuntu-18.04'
            gcc: '8'
            cmake: '3.25'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: false
          - base: 'ubuntu-20.04'
            gcc: '10'
            cmake: '3.31.5'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: false
          - base: 'ubuntu-22.04'
            gcc: '11'
            cmake: '3.31.5'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: false
          - base: 'ubuntu-24.04'
            gcc: '14'
            cmake: '3.31.5'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: false
          - base: 'debian-10'
            gcc: '8'
            cmake: '3.25'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: false
          - base: 'debian-11'
            gcc: '10'
            cmake: '3.31.5'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: false
          - base: 'debian-12'
            gcc: '12'
            cmake: '3.31.5'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: false
          - base: 'alpine-3.18'
            gcc: '12'
            cmake: '3.26.5'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: true
          - base: 'alpine-3.21'
            gcc: '14'
            cmake: '3.31.3'
            vcpkg: '2024.05.24'
            runner: ubuntu-24.04
            build: true

    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        if: matrix.build == true
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: matrix.build == true
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image ${{ matrix.base }}
        if: matrix.build == true
        run: |
          docker build ${{ github.workspace }}/src/${{ matrix.base }} --tag ghcr.io/smkanadl/docker-gcc-cmake:${{ matrix.base }}-gcc-${{ matrix.gcc }}-cmake-${{ matrix.cmake }}-vcpkg-${{ matrix.vcpkg }} --tag ghcr.io/smkanadl/docker-gcc-cmake:${{ matrix.base }}
          docker push ghcr.io/smkanadl/docker-gcc-cmake:${{ matrix.base }}-gcc-${{ matrix.gcc }}-cmake-${{ matrix.cmake }}-vcpkg-${{ matrix.vcpkg }}
          docker push ghcr.io/smkanadl/docker-gcc-cmake:${{ matrix.base }}
